name: CI/CD
on:
  push
  # pull_request:
  #   types:
  #     - closed

jobs:
  build-vite:
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version that your project requires

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
    
      - run: ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build-vite

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ~/public_html/dist
      
      - name: List files
        run: ls -R
      
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd public_html

            rm -r remote
            mkdir remote2