name: CD - Deploy to VPS

on:
  workflow_run:
    workflows: ["CI - Build on Merge to Dev"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
      
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd public_html

            rm -r remote
            mkdir remote
            cp -r ./dist/* ./remote/
            
