name: CD - Deploy to VPS

on:
  push
  # workflow_run:
  #   workflows: ["CI - Build on Merge to Dev"]
  #   types:
  #     - completed

jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            whoami
            mkdir test1
